// STATUS BAR ACTIONS

export const SHOW_PROFILE = "SHOW_PROFILE";
export const HIDE_PROFILE = "HIDE_PROFILE";
export const SHOW_STATUS = "SHOW_STATUS";
export const HIDE_STATUS = "HIDE_STATUS";
export const TOGGLE_NEW_CHAT = "TOGGLE_NEW_CHAT";
export const TOGGLE_OPTIONS = "TOGGLE_OPTIONS";

// GROUP INFO ACTIONS
export const SHOW_GROUP_INFO = "SHOW_GROUP_INFO";
// GROUP INFO ACTIONS
export const HIDE_GROUP_INFO = "HIDE_GROUP_INFO";

// SEARCH BARS ACTION
export const TOGGLE_MSG_SEARCH = "TOGGLE_OPTIONS";

// NOT IN USE
export const DISPLAY_CONTEXT_MENU = "DISPLAY_CONTEXT_MENU";
// group starred msgs
export const TOGGLE_GRP_STARRED_MSGS = "TOGGLE_GRP_STARRED_MSGS";

//ACTIONS FOR OPTIONS WHICH IS A CHILD OF IN STATUS BAR ACTIONS
export const TOGGLE_NEW_GROUP = "TOGGLE_NEW_GROUP";
export const TOGGLE_ARCHIVE = "TOGGLE_ARCHIVE";
export const TOGGLE_STARRED_MSGS = "TOGGLE_STARRED_MSGS";
export const DISPLAY_SETTINGS = "DISPLAY_SETTINGS";
export const DISPLAY_SECURITY = "DISPLAY_SECURITY";
export const DISPLAY_PRIVACY = "DISPLAY_PRIVACY";

export const LOGOUT = "LOGOUT";

// THIS ACTIONS IS FROM SETTINGS
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const TOGGLE_THEME = "TOGGLE_THEME";
export const TOGGLE_CHAT_WALLPAPER = "TOGGLE_CHAT_WALLPAPER";
export const TOGGLE_KEYBOARD_SHORTCUTS = "TOGGLE_KEYBOARD_SHORTCUTS";
export const TOGGLE_BLOCKED_CONTACTS = "TOGGLE_BLOCKED_CONTACTS";
export const TOGGLE_HELP = "TOGGLE_HELP";

// ACTIONS FOR GROUP CONTEXT MENU

export const ARCHIVE_CHAT = "ARCHIVE_CHAT";
export const MUTE_NOTIFICATION = "MUTE_NOTIFICATION";
export const EXIT_GROUP = "EXIT_GROUP";
export const PIN_CHAT = "PIN_CHAT";
export const MARK_AS_READ = "MARK_AS_READ";

// SELECT CONTACTS

export const SELECT_CONTACTS = "SELECT_CONTACTS";
export const SEARCH_GROUP_PARTICIPANTS = "SEARCH_GROUP_PARTICIPANTS";
export const CLOSE_SEARCH_GROUP_PARTICIPANTS =
  "CLOSE_SEARCH_GROUP_PARTICIPANTS";

// conditional rendering

export const SHOW_GROUP_MSG = "SHOW_GROUP_MSG";
export const LINK_SETTINGS_AND_PROFILE = "LINK_SETTINGS_AND_PROFILE";
